#+title: Filmsnet

* Filmsnet
Две части фич - для конечного пользователя и для админа сервера. Меня больше интересуют фишки для админа: возможность по торрент протоколу обмениваться фильмами и сериалами. Возможность редактировать метаданные. А главное, метаданные, видеопотоки, субтитры и аудиофайлы восприниматься должны отдельно, чтобы человек мог отдельно скачивать медиапоток, отдельно метаданные, отдельные желаемые озвучки. Разумеется, при воспроизведении оно для конечного пользователя должно выглядеть цельно, разве что он может выбрать что воспроизводить из списка возможностей.
** Main, admin, server side features
- sf.00 Целевые платформы: Linux, FreeBSD, Желательно Windows, для людей нетрадиционной ориентации.
- sf.01 Загрузка видеофайлов, с их разбивкой отдельно на сам видеопоток(и), аудиопоток(и), субтитры и метаданные ко всему вышеперечисленному.
- sf.02 Несколько серверов могут объединяться в сеть. Человек у себя вносит в белый список доверенные сервера, и оставляет настройку, дать доступ к своему контенту только серверам из списка, или всем в цепочке. Возможно, имеет смысл настраивать длинну доверенной цепочки для того, чтобы админу было проще для себя оптимизировать нагрузку на свой сервер и/или защитить себя юридически, чтобы формально не распространять "пиратский" контент на неограниченный круг лиц.
- sf.03 Сервера внутри сети могут обмениваться контентом по торрент протоколу.
- sf.04 Возможно, стоит добавить возможность шифровать торрент протокол. Да, Германия, я смотрю на тебя.
  Ну и/или добавить возможность скачивать контент традиционно, если дружеский сервер на то дал согласие. Но звучит так себе, на самом деле, лучше просто позаботиться о хотя бы примитивной маскировке.
- sf.05 Если контент находится на нескольких серверах внутри сети, клиент должен получать трафик распределённо ото всех участников, снижая тем самым нагрузку на каждого в отдельности. Сетью тут стоит понимать, если у двух админов оба их сервера друг у друга в белом списке. Админ может выключить это ограничение, и раздавать трафик на всех, кто запрашивает, по торрент-протоколу. Или наоборот, строго отдавать трафик только своим клиентам.
  Возможно, имеет смысл сделать такую же настройку по длинне цепочки, как и с фичей по скачиванию контента sf.02
- sf.06 Для обратной совместимости с чем только можно, должна быть возможность скачать единицу контента (фильм, серия сериала, клип) одним файлом.
- sf.07 Если это не будет вредить производительности, можно оставить возможность хранить единицу контента одним файлом непосредственно на носителе, т.е. конвертировать все эти отдельные файлы в один, с удобным, интуитивно-понятным поиском внутри файловой системы Скорее всего, это будет вредить производительности
** Client features
В целом, в качестве референса можно использовать Jellyfin и Нетфликс. Единственное, Jellyfin просто отвратительно работает с многоязычной медиатекой, и это стоит учитывать. Нетфликс, вроде, получше, но не идеально, по моим воспоминанием. Если вдруг у клиента в предпочтения больше одного языка, он сходил с ума, но это не точно, я давно нетфликсом не пользовался.
Идея в том, чтобы любому человеку, многоязычному, одноязычному, было легко найти контент, в нужном языковом диапозоне, если он хочет или он с этим окей с субтитрами, и с запоминанем выбора нужного языка/озвучки вплоть до тайтла/сериала или фильма.
- cf.00 Целевые платформы клиентов: Browser (Firefox, Chromium), Android, IOS, Windows, MacOS, Linux, FreeBSD.
  Можно смотреть в сторону использования фреймворка вроде Electron, или любой другой, использующий chromium под капотом, когда запускается вне браузера, но я лично довольно скептично отношусь к идее возить браузер для приложения. Тем не менее, это действительно, наверное, самый дешёвый способ сделать одно приложение для всего. Но производительность стоит проверить, эти приложения очень часто довольно херово оптимизированы в итоге, и потребляют тонну ресурсов. Не сами они даже, а chromium. Ну вы поняли.

* Madshare
Концепция для аудио, преимущественно музыки
** server side
- Server should contain audio files on a server disk, optional with s3
- Audio files and those metadata should be separated.
- Server lets upload, download and playing audio files with and without decoding (by using ffmpeg)
- Server has one admin account.
- Server has clients accounts.
- A user could not to upload new audio files without admin permission.
- By default server should not to allow download and play a media file for unathorized users to prevent a legal attack.
- Server can connecting with another servers by a federation protocol
- Connected servers could be balancers for streaming music files if they have same audio files.
- Connected servers could download and upload audio files to each other. Each audio file is verified by his hash sum.
- Servers can block spam servers those files are scam (untrusted servers). Each admin aprooves or disaprooves media files, that he can see in madnetwork. If server has critical mass of untrusted media, his files have low rating and clients don't see those media. Prevent spam attack on the madnetwork.
** client side
- Client should allow to discover audio files on the server
- Client should allow to discover audio files on the server's friends and madnetwork
- Client should allow to play audio files
- Client should allow to download audio files
