//go:build tests && !nofederation

package main

// One lab node: a real madshare process with its own data dir, database,
// federation identity and ports, plus the API client used to bootstrap and
// drive it.
//
// Everything here talks to madshare over its public HTTP API rather than
// reaching into its packages. That is the point of the lab — the in-process
// chaos suite (federation/chaos_test.go) already exercises the internals, and
// what it cannot show is a real process doing the real startup: migrations,
// the first-run admin, the forced password change, the analysis pipeline, the
// browse endpoints the web UI actually calls.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

// bootstrapPassword is the first-run admin password every node starts with, and
// adminPassword is what it is changed to (madshare forces a change before it
// will mint a token). Both are fixed and public on purpose: a lab node is
// disposable and loopback-only, and a generated secret nobody can type would
// only make the lab harder to poke at by hand. This is also exactly why meshlab
// must never bind anything off-host — see the safety note in main.go.
const (
	bootstrapPassword = "meshlab-bootstrap-pw"
	adminPassword     = "meshlab-admin-pw"
	adminUser         = "admin"
)

// node is one madshare server under meshlab's supervision.
type node struct {
	name     string   // "a", "b", …
	dir      string   // data dir, under the lab root
	httpAdr  string   // 127.0.0.1:port — the API and web UI
	underlay string   // 127.0.0.1:port — the yggdrasil peering it listens on
	scheme   string   // "tcp" or "quic": the underlay transport
	peers    []string // underlay URIs this node dials (proxy addresses)

	bin    string
	logf   *os.File
	client *http.Client

	mu     sync.Mutex
	cmd    *exec.Cmd
	token  string // bearer token, minted after bootstrap
	pubkey string // federation public key, read back after start
	card   json.RawMessage
}

// configFile renders the node's madshare.toml.
//
// reachable_window_sec is set to the floor madshare allows (120 s). The lab
// cannot shrink it further — config.Load clamps anything lower with a warning —
// so an availability walkthrough waits two minutes for a friend to go stale.
// That is a real property of the product, not a lab limitation to work around,
// and it is why `meshlab status` prints each friend's last_seen age: you watch
// it climb rather than guess.
func (n *node) configFile() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by meshlab — disposable lab node %q\n", n.name)
	fmt.Fprintf(&b, "data_dir = %q\n\n", n.dir)
	fmt.Fprintf(&b, "[[listen]]\naddr = \"127.0.0.1\"\nport = %s\nserve = [\"api\", \"webui\", \"admin\"]\n\n", portOf(n.httpAdr))
	fmt.Fprintf(&b, "[auth]\ninitial_admin_user = %q\ninitial_admin_password = %q\n\n", adminUser, bootstrapPassword)
	fmt.Fprintf(&b, "[storage]\nmax_upload_mb = 500\n\n")
	fmt.Fprintf(&b, "[federation]\nenabled = true\nname = %q\n", "meshlab-"+n.name)
	fmt.Fprintf(&b, "key_file = %q\n", filepath.Join(n.dir, "federation.key"))
	fmt.Fprintf(&b, "listen = [\"%s://%s\"]\n", n.scheme, n.underlay)
	if len(n.peers) > 0 {
		quoted := make([]string, len(n.peers))
		for i, p := range n.peers {
			quoted[i] = fmt.Sprintf("%q", p)
		}
		fmt.Fprintf(&b, "peers = [%s]\n", strings.Join(quoted, ", "))
	}
	fmt.Fprintf(&b, "reachable_window_sec = %d\n", reachableWindowSec)
	return b.String()
}

const reachableWindowSec = 120 // config.MinReachableWindowSec — the lab cannot go lower

// start writes the config and launches the process. It does not wait for
// readiness; see waitReady.
func (n *node) start() error {
	if err := os.MkdirAll(n.dir, 0o755); err != nil {
		return err
	}
	cfgPath := filepath.Join(n.dir, "madshare.toml")
	if err := os.WriteFile(cfgPath, []byte(n.configFile()), 0o600); err != nil {
		return err
	}
	if n.logf == nil {
		f, err := os.OpenFile(filepath.Join(n.dir, "madshare.log"), os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
		if err != nil {
			return err
		}
		n.logf = f
	}
	cmd := exec.Command(n.bin, "-config", cfgPath)
	// madshare resolves template paths relative to CWD in a nowebui-less build,
	// and the source endpoint reads git from it, so run each node from the repo
	// root rather than its data dir.
	cmd.Dir = repoRoot
	cmd.Stdout, cmd.Stderr = n.logf, n.logf
	if err := cmd.Start(); err != nil {
		return fmt.Errorf("start %s: %w", n.name, err)
	}
	n.mu.Lock()
	n.cmd = cmd
	n.mu.Unlock()
	return nil
}

// stop kills the process and waits for it. Identity survives: the key file
// stays in the data dir, so a restart is the same node returning rather than a
// new one — losing federation.key would break every friendship it has.
func (n *node) stop() {
	n.mu.Lock()
	cmd := n.cmd
	n.cmd = nil
	n.mu.Unlock()
	if cmd == nil || cmd.Process == nil {
		return
	}
	cmd.Process.Signal(os.Interrupt)
	done := make(chan struct{})
	go func() { cmd.Wait(); close(done) }()
	select {
	case <-done:
	case <-time.After(10 * time.Second):
		cmd.Process.Kill()
		<-done
	}
}

func (n *node) running() bool {
	n.mu.Lock()
	defer n.mu.Unlock()
	return n.cmd != nil
}

// waitReady polls /healthz until the server answers.
func (n *node) waitReady(timeout time.Duration) error {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if !n.running() {
			return fmt.Errorf("node %s exited during startup — see %s", n.name, filepath.Join(n.dir, "madshare.log"))
		}
		resp, err := n.client.Get(n.url("/healthz"))
		if err == nil {
			resp.Body.Close()
			if resp.StatusCode == http.StatusOK {
				return nil
			}
		}
		time.Sleep(200 * time.Millisecond)
	}
	return fmt.Errorf("node %s not ready within %v — see %s", n.name, timeout, filepath.Join(n.dir, "madshare.log"))
}

func (n *node) url(path string) string { return "http://" + n.httpAdr + path }

// ── Bootstrap ────────────────────────────────────────────────────────────────

// bootstrap walks the first-run sequence: log in with the config's initial
// password, complete the forced change, then mint a bearer token.
//
// The order is forced by the server: POST /api/auth/tokens refuses an identity
// with PasswordChangeRequired set (api/auth_handlers.go), because minting new
// credentials is an action rather than part of the change-password flow. Skip
// the change and every later admin call fails with a message about the password,
// which reads like an auth bug and is not one.
func (n *node) bootstrap() error {
	jar, err := newJar()
	if err != nil {
		return err
	}
	n.client.Jar = jar

	if err := n.postJSON("/api/auth/login", map[string]string{
		"username": adminUser, "password": bootstrapPassword,
	}, nil); err != nil {
		// A restarted node already has its password changed; the bootstrap one
		// is gone. Try the changed password before giving up.
		if err2 := n.postJSON("/api/auth/login", map[string]string{
			"username": adminUser, "password": adminPassword,
		}, nil); err2 != nil {
			return fmt.Errorf("login on %s: %w", n.name, err)
		}
	} else if err := n.postJSON("/api/auth/password", map[string]string{
		"old_password": bootstrapPassword, "new_password": adminPassword,
	}, nil); err != nil {
		return fmt.Errorf("forced password change on %s: %w", n.name, err)
	}

	var tok struct {
		Token string `json:"token"`
	}
	if err := n.postJSON("/api/auth/tokens", map[string]any{
		"name": "meshlab", "expires_in_days": 1,
	}, &tok); err != nil {
		return fmt.Errorf("token mint on %s: %w", n.name, err)
	}
	if tok.Token == "" {
		return fmt.Errorf("token mint on %s returned no token", n.name)
	}
	n.mu.Lock()
	n.token = tok.Token
	n.mu.Unlock()
	return n.readIdentity()
}

// readIdentity caches the node's federation key and card.
func (n *node) readIdentity() error {
	var st struct {
		Enabled bool `json:"enabled"`
		Node    struct {
			PublicKey string          `json:"public_key"`
			Address   string          `json:"address"`
			Card      json.RawMessage `json:"card"`
		} `json:"node"`
	}
	if err := n.getJSON("/api/admin/federation", &st); err != nil {
		return fmt.Errorf("federation status on %s: %w", n.name, err)
	}
	if !st.Enabled {
		return fmt.Errorf("node %s reports federation disabled — was it built with -tags nofederation?", n.name)
	}
	n.mu.Lock()
	n.pubkey, n.card = st.Node.PublicKey, st.Node.Card
	n.mu.Unlock()
	return nil
}

func (n *node) publicKey() string {
	n.mu.Lock()
	defer n.mu.Unlock()
	return n.pubkey
}

func (n *node) nodeCard() json.RawMessage {
	n.mu.Lock()
	defer n.mu.Unlock()
	return n.card
}

// ── HTTP ─────────────────────────────────────────────────────────────────────

func (n *node) do(method, path string, body io.Reader, contentType string, out any) error {
	req, err := http.NewRequest(method, n.url(path), body)
	if err != nil {
		return err
	}
	if contentType != "" {
		req.Header.Set("Content-Type", contentType)
	}
	n.mu.Lock()
	tok := n.token
	n.mu.Unlock()
	if tok != "" {
		req.Header.Set("Authorization", "Bearer "+tok)
	}
	resp, err := n.client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	raw, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return fmt.Errorf("%s %s: %s: %s", method, path, resp.Status, strings.TrimSpace(string(raw)))
	}
	if out != nil {
		if err := json.Unmarshal(raw, out); err != nil {
			return fmt.Errorf("%s %s: decoding response: %w", method, path, err)
		}
	}
	return nil
}

func (n *node) postJSON(path string, in, out any) error {
	b, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return n.do(http.MethodPost, path, bytes.NewReader(b), "application/json", out)
}

func (n *node) getJSON(path string, out any) error {
	return n.do(http.MethodGet, path, nil, "", out)
}

// patchJSON is the access endpoints' verb (recordings carry their license, guest
// flag and share depth behind PATCH, since a request names only the fields it
// changes).
func (n *node) patchJSON(path string, in, out any) error {
	b, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return n.do(http.MethodPatch, path, bytes.NewReader(b), "application/json", out)
}

// rawGet fetches a path and returns the status and body without insisting on
// JSON or on success — the check pass asserts against refusals, where `do`'s
// error-on-non-2xx would throw away the status it is testing for. The timeout is
// per call because a madnetwork stream that has to give up on every holder takes
// far longer than an admin API round-trip.
func (n *node) rawGet(path string, timeout time.Duration) (int, []byte, error) {
	req, err := http.NewRequest(http.MethodGet, n.url(path), nil)
	if err != nil {
		return 0, nil, err
	}
	n.mu.Lock()
	tok := n.token
	n.mu.Unlock()
	if tok != "" {
		req.Header.Set("Authorization", "Bearer "+tok)
	}
	client := &http.Client{Timeout: timeout, Jar: n.client.Jar}
	resp, err := client.Do(req)
	if err != nil {
		return 0, nil, err
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(io.LimitReader(resp.Body, 256<<20))
	return resp.StatusCode, body, nil
}

// upload posts one file to /files/upload as multipart, the same request the
// upload page makes.
func (n *node) upload(path string, out any) error {
	f, err := os.Open(path)
	if err != nil {
		return err
	}
	defer f.Close()
	var body bytes.Buffer
	mw := multipart.NewWriter(&body)
	part, err := mw.CreateFormFile("file", filepath.Base(path))
	if err != nil {
		return err
	}
	if _, err := io.Copy(part, f); err != nil {
		return err
	}
	if err := mw.Close(); err != nil {
		return err
	}
	return n.do(http.MethodPost, "/files/upload", &body, mw.FormDataContentType(), out)
}

// ── Ports ────────────────────────────────────────────────────────────────────

// reservePort takes a free loopback port by binding and closing it. The window
// between close and reuse is inherent to the idiom (the chaos suite has the
// same note); a lab starts a handful of nodes once, so it stays narrow.
func reservePort() (string, error) {
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		return "", err
	}
	addr := ln.Addr().String()
	ln.Close()
	return addr, nil
}

// reserveUDPPort is the datagram counterpart — TCP and UDP port spaces are
// separate, so a quic:// underlay must probe the one it will bind.
func reserveUDPPort() (string, error) {
	c, err := net.ListenPacket("udp", "127.0.0.1:0")
	if err != nil {
		return "", err
	}
	addr := c.LocalAddr().String()
	c.Close()
	return addr, nil
}

func portOf(hostport string) string {
	_, port, err := net.SplitHostPort(hostport)
	if err != nil {
		return hostport
	}
	return port
}
